# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: pod
    spec:
      containers:
        - name: web
          image: ghcr.io/coinhub-uit/web:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
          env:
            - name: NEXT_PUBLIC_API_SERVER_URL
              value: service.server:3000
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: authSecret
