# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
spec:
  type: kv-v2
  mount: secret
  path: web/config
  destination:
    name: secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
