apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
spec:
  type: kv-v2
  mount: secret
  path: web/config
  destination:
    name: secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
