# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2-standalone-strict/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
