---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-config
spec:
  type: kv-v2
  mount: secret
  path: supabase/config
  destination:
    name: secret-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-database
spec:
  type: kv-v2
  mount: secret
  path: supabase/database
  destination:
    name: secret-database
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-smtp
spec:
  type: kv-v2
  mount: secret
  path: supabase/smtp
  destination:
    name: secret-smtp
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-dashboard
spec:
  type: kv-v2
  mount: secret
  path: supabase/dashboard
  destination:
    name: secret-dashboard
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
