apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coinhub-server
spec:
  project: default
  source:
    repoURL: https://github.com/coinhub-uit/argocd-manifest.git
    path: apps/server
  destination:
    namespace: coinhub-server
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - Prune=true
    - CreateNamespace=true
    - ServerSideApply=true
  dependsOn:
    - coinhub-supabase
