apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: coinhub
  namespace: gateway
  annotations:
    networking.istio.io/service-type: LoadBalancer # ClusterIP
spec:
  gatewayClassName: istio
  listeners:
    - name: server-http
      port: 80
      protocol: HTTP
      hostname: "server.coinhub.kevinnitro.duckdns.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              coinhub-server-gateway: "true"
    - name: server-https
      port: 443
      protocol: HTTPS
      hostname: "server.coinhub.kevinnitro.duckdns.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              coinhub-server-gateway: "true"
    - name: web-http
      port: 80
      protocol: HTTP
      hostname: "web.coinhub.kevinnitro.duckdns.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              coinhub-web-gateway: "true"
    - name: web-https
      port: 443
      protocol: HTTPS
      hostname: "web.coinhub.kevinnitro.duckdns.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              coinhub-web-gateway: "true"
    - name: argo-cd-http
      port: 80
      protocol: HTTP
      hostname: "argocd.coinhub.kevinnitro.duckdns.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              argocd-gateway: "true"
