# yaml-language-server: schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: argo-cd
    name: argo-cd
    version: 8.1.4
    namespace: argocd
    includeCRDs: true
    repo: oci://ghcr.io/argoproj/argo-helm
    valuesFile: ./value.yaml

images:
  - name: quay.io/argoproj/argocd
    newTag: v3.0.11
