# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.27.0
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.27.0
    releaseName: istiod
    namespace: istio-system
    valuesFile: ./values/istiod.yaml
  - name: cni
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.27.0
    releaseName: istio-cni
    namespace: istio-system
    valuesFile: ./values/cni.yaml
  - name: ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.27.0
    releaseName: ztunnel
    namespace: istio-system
