# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2-standalone-strict/deployment.json
apiVersion: app/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: coinhub
  template:
    spec:
      containers:
        - name: coinhub-server
          image: coinhub-server
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: config-map
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: adminJwtSecret
                  name: secret
            - name: ADMIN_JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  key: adminJwtRefreshSecret
                  name: secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: openaiApiKey
                  name: secret
            - name: OPENAI_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: openaiBaseUrl
                  name: secret
            - name: VNPAY_SECURE_SECRET
              valueFrom:
                secretKeyRef:
                  key: vnpaySecureSecret
                  name: secret
            - name: VNPAY_TMN_CODE
              valueFrom:
                secretKeyRef:
                  key: vnpayTmnCode
                  name: secret
