# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    spec:
      containers:
        - name: server
          image: ghcr.io/coinhub-uit/server:latest
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: config-map
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: secret-supabase-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-supabase-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: secret-supabase-database
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  key: serviceKey
                  name: secret-supabase-config
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: secret-supabase-config
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: adminJwtSecret
                  name: secret-server
            - name: ADMIN_JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  key: adminJwtRefreshSecret
                  name: secret-server
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: openaiApiKey
                  name: secret-server
            - name: OPENAI_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: openaiBaseUrl
                  name: secret-server
            - name: VNPAY_SECURE_SECRET
              valueFrom:
                secretKeyRef:
                  key: vnpaySecureSecret
                  name: secret-server
            - name: VNPAY_TMN_CODE
              valueFrom:
                secretKeyRef:
                  key: vnpayTmnCode
                  name: secret-server
          volumeMounts:
            - name: assets
              mountPath: /app/assets/uploads
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: pvc-assets
