# yaml-language-server: schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
labels:
  - pairs:
      app: server
    includeSelectors: true
resources:
  - ./namespace.yaml
  - ./configmap.yaml
  - ./service-account.yaml
  - ./vault-auth.yaml
  - ./vault-static-secret.yaml
  - ./persistent-volume-claim.yaml
  - ./deployment.yaml
  - ./service.yaml
