---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-server
spec:
  type: kv-v2
  mount: secret
  path: server/config
  destination:
    name: secret-server
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-supabase-config
spec:
  type: kv-v2
  mount: secret
  path: supabase/config
  destination:
    name: secret-supabase-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-supabase-database
spec:
  type: kv-v2
  mount: secret
  path: supabase/database
  destination:
    name: secret-supabase-database
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
