apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coinhub-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: &repo https://github.com/coinhub-uit/argocd-manifest.git
        revision: HEAD
        directories:
          - path: "apps/*/overlays/dev"
  template:
    metadata:
      name: "{{.path.basename}}-dev"
    spec:
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Prune=true
      - ServerSideApply=true
      - CreateNamespace=true
