apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coinhub-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: &repo https://github.com/coinhub-uit/argocd-manifest.git
        revision: HEAD
        directories:
          - path: "apps/*/overlays/dev"
  template:
    metadata:
      name: "{{index .path.segments 1}}-dev"
    spec:
      project: default # This is required idk ohm
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - Prune=true
          - ServerSideApply=true
          - CreateNamespace=true
        retry:
          limit: 5
