apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: coinhub-supabase
  namespace: argocd

spec:
  project: default
  source:
    chart: supabase
    repoURL: https://tokens-studio.github.io/helm/
    targetRevision: 1.0.0
    helm:
      releaseName: supabase
      valueFiles:
        - ./value.yaml
  destination:
    namespace: coinhub-supabase
    name: in-cluster
